# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'congresistas.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class clase_congrasistas(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(552, 459)
        font = QtGui.QFont()
        font.setFamily("Oswald SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        self.lbl_titulo = QtWidgets.QLabel(Dialog)
        self.lbl_titulo.setGeometry(QtCore.QRect(200, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Oswald SemiBold")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setStyleSheet("font: 63 24pt \"Oswald SemiBold\";")
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.btn_Cerrar = QtWidgets.QPushButton(Dialog)
        self.btn_Cerrar.setGeometry(QtCore.QRect(370, 410, 81, 41))
        self.btn_Cerrar.setObjectName("btn_Cerrar")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 80, 232, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rbt_opcion1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbt_opcion1.setObjectName("rbt_opcion1")
        self.verticalLayout.addWidget(self.rbt_opcion1)
        self.rbt_opcion2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbt_opcion2.setObjectName("rbt_opcion2")
        self.verticalLayout.addWidget(self.rbt_opcion2)
        self.rbt_opcion3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbt_opcion3.setObjectName("rbt_opcion3")
        self.verticalLayout.addWidget(self.rbt_opcion3)
        self.rbt_opcion4 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbt_opcion4.setObjectName("rbt_opcion4")
        self.verticalLayout.addWidget(self.rbt_opcion4)
        self.rbt_opcion5 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbt_opcion5.setObjectName("rbt_opcion5")
        self.verticalLayout.addWidget(self.rbt_opcion5)
        self.rbt_opcion6 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbt_opcion6.setObjectName("rbt_opcion6")
        self.verticalLayout.addWidget(self.rbt_opcion6)
        self.rbt_opcion8 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbt_opcion8.setObjectName("rbt_opcion8")
        self.verticalLayout.addWidget(self.rbt_opcion8)
        self.lbl_tituloresult = QtWidgets.QLabel(Dialog)
        self.lbl_tituloresult.setGeometry(QtCore.QRect(350, 70, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Oswald SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tituloresult.setFont(font)
        self.lbl_tituloresult.setObjectName("lbl_tituloresult")
        self.lbl_resultado = QtWidgets.QLabel(Dialog)
        self.lbl_resultado.setGeometry(QtCore.QRect(270, 110, 261, 291))
        self.lbl_resultado.setText("")
        self.lbl_resultado.setObjectName("lbl_resultado")
        self.btn_Aceptar = QtWidgets.QPushButton(Dialog)
        self.btn_Aceptar.setGeometry(QtCore.QRect(460, 410, 81, 41))
        self.btn_Aceptar.setObjectName("btn_Aceptar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_titulo.setText(_translate("Dialog", "Congresistas"))
        self.btn_Cerrar.setText(_translate("Dialog", "Examinar"))
        self.rbt_opcion1.setText(_translate("Dialog", "1-Asistencias"))
        self.rbt_opcion2.setText(_translate("Dialog", "2-Sin excusa"))
        self.rbt_opcion3.setText(_translate("Dialog", "3-Promedio"))
        self.rbt_opcion4.setText(_translate("Dialog", "4-Fallas de circunscripcion"))
        self.rbt_opcion5.setText(_translate("Dialog", "5-Excusa medica"))
        self.rbt_opcion6.setText(_translate("Dialog", "6-Fecha de fallas"))
        self.rbt_opcion8.setText(_translate("Dialog", "7-Mes selecionado"))
        self.lbl_tituloresult.setText(_translate("Dialog", "Resultado"))
        self.btn_Aceptar.setText(_translate("Dialog", "Aceptar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = clase_congrasistas()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
